// STOCK MUTATIONS
export const MUTATION_CURRENT_PRICE = 'stock/MUTATION_CURRENT_PRICE'


// STOCK ACTIONS
export const ACTION_CURRENT_PRICE = 'stock/ACTION_CURRENT_PRICE'

// STOCK GETTERS
export const GETTER_STOCK = 'stock/GETTER_STOCK'