// STOCK MUTATIONS
export const MUTATION_CURRENT_PRICE = 'stock/MUTATION_CURRENT_PRICE'

// STOCK ACTIONS
export const ACTION_CURRENT_PRICE = 'stock/ACTION_CURRENT_PRICE'

// STOCK GETTERS
export const GETTER_ALL_STOCK = 'stock/GETTER_ALL_STOCK'
export const GETTER_A_STOCK = 'stock/GETTER_A_STOCK'