// STOCK MUTATIONS
export const MUTATION_CURRENT_PRICE = 'stock/MUTATION_CURRENT_PRICE'
export const MUTATION_SET_STATE = 'stock/MUTATION_SET_STATE'

// STOCK ACTIONS
export const ACTION_CURRENT_PRICE = 'stock/ACTION_CURRENT_PRICE'
export const ACTION_EXPORT_STATE_TO_FIREBASE = 'stock/ACTION_EXPORT_STATE_TO_FIREBASE'
export const ACTION_IMPORT_STATE_FROM_FIREBASE = 'stock/ACTION_IMPORT_STATE_FROM_FIREBASE'

// STOCK GETTERS
export const GETTER_ALL_STOCK = 'stock/GETTER_ALL_STOCK'
export const GETTER_A_STOCK = 'stock/GETTER_A_STOCK'