// PORTFOLIO MUTATIONS
export const MUTATION_BUY_STOCK = 'portfolio/MUTATION_BUY_STOCK'
export const MUTATION_SELL_STOCK = 'portfolio/MUTATION_SELL_STOCK'
export const MUTATION_SET_STATE = 'portfolio/MUTATION_SET_STATE'

// PORTFOLIO ACTIONS
export const ACTION_BUY_STOCK = 'portfolio/ACTION_BUY_STOCK'
export const ACTION_SELL_STOCK = 'portfolio/ACTION_SELL_STOCK'
export const ACTION_EXPORT_STATE_TO_FIREBASE = 'portfolio/ACTION_EXPORT_STATE_TO_FIREBASE'
export const ACTION_IMPORT_STATE_FROM_FIREBASE = 'portfolio/ACTION_IMPORT_STATE_FROM_FIREBASE'

// PORTFOLIO GETTERS
export const GETTER_SALDO = 'portfolio/GETTER_SALDO'
export const GETTER_SALDO_READABLE = 'portfolio/GETTER_SALDO_READABLE'
export const GETTER_PORTOFOLIO_STOCK = 'portfolio/GETTER_PORTOFOLIO_STOCK'
export const GETTER_TOTAL_PROFIT = 'portfolio/GETTER_TOTAL_PROFIT'
export const GETTER_STATE = 'portfolio/GETTER_STATE'
export const GETTER_PORTOFOLIO_ALL_STOCK = 'portfolio/GETTER_PORTOFOLIO_ALL_STOCK'
